### PR TITLE
Utils localization

### LINKED ISSUE #251: Extends moment
In the case you are using extends moment (for example moment-timezone) it will have some conflicts, because material-ui-pickers imports moment from node_modules without possibility to pass extended moment directly.

Seems like the way to fix it pass moment to MomentUtils or setup moment in constructor. I can contribute if needed, let me know if you have any ideas or plans to fix it.

Another example it's a locale.
For example in main project you are using locale.

```
import moment from 'moment';
moment.locale('sv');
export default moment;
```

Locale will not work with material-ui-pickers, because it uses node_modules/moment

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0-rc.1       |
| material-ui         | 1.0.0-beta.32        |
| React               |  16.2.0       |
| Browser             |  Any       |
| Platform            | MacOS        |

## Steps to reproduce
1. Use moment-timezone in main project.
```
import moment from 'moment-timezone';
moment.tz.setDefault(timezone);
export default moment;
```
2. Using DateTime picker will use your local timezone and have conflicts with current code base
3. As a result your moment logic will have timezone conflict with pickers if you use another timexone then local one.

## Expected behavior
Possibility to pass moment to MomentUtils

## Actual behavior
Using moment from node_modules

### PR DESCRIPTION
**Pull request by dmtrKovalenko**
Changed utils to be the instantiate object, add prop `locale` to the `MuiPickersUtilsProvider`, which will contain localization object for date-fns and just string for moment.

Also add an ability to pass moment object with selected locale and timezone defaults, which actually closes #251

### CODE REVIEW

File: lib/src/utils/moment-utils.js [hunk 1]
```diff
@@ -1,123 +1,129 @@
...
-  static getStartOfMonth(date) {
-    return date.clone().startOf('month');
+  getStartOfMonth(date) {
+    return this.moment(date).clone().startOf('month');
   }
 
-  static getNextMonth(date) {
-    return date.clone().add(1, 'month');
+  getNextMonth(date) {
+    return this.moment(date).clone().add(1, 'month');
```
Comment (alitaheri) [inline lib/src/utils/moment-utils.js]: Why only these two functions get to call `this.moment()`.

File: lib/src/utils/MuiPickersUtilsProvider.jsx [hunk 2]
```diff
@@ -4,16 +4,24 @@ import PropTypes from 'prop-types';
 export default class MuiPickersUtilsProvider extends PureComponent {
   static propTypes = {
     utils: PropTypes.func.isRequired,
+    locale: PropTypes.oneOfType([PropTypes.object, PropTypes.string]),
     children: PropTypes.element.isRequired,
+    moment: PropTypes.func,
```
Comment (cherniavskii) [inline lib/src/utils/MuiPickersUtilsProvider.jsx]: Why moment needs to be passed to utils? Won't importing `moment` in `moment-utils` and calling `moment.locale()` do the trick?

I'm guessing it's about sharing same moment instance between `material-ui-pickers` and rest of application, but I always thought that locale is set globally per app.

Just asking to make sure we can't avoid this :)

Comment (dmtrKovalenko) [reply lib/src/utils/MuiPickersUtilsProvider.jsx]: @cherniavskii I have tried, but i gave up. 
If you want - you can try it in this branch :)

Comment (alitaheri) [reply lib/src/utils/MuiPickersUtilsProvider.jsx]: @cherniavskii We shouldn't set the locale globally, we cannot assume how the user is going to use this library, or with how many concurrent locales.

besides, the `locale` field isn't even used.

We have 2 options:

1. leave the locale setup to the user.
2. get the locale from the user in constructor and use the [local locale](https://momentjs.com/docs/#/i18n/instance-locale/) feature.

Comment (dmtrKovalenko) [reply lib/src/utils/MuiPickersUtilsProvider.jsx]: @alitaheri @cherniavskii 
User can also use local locale featues by himself and pass already localed moment instance to the pickers. Because of global selecting locale is really weird in moment maybe we will merge and release this feature and then will redo it if possible :) 
Because I know that a lot of people depends on it.

Comment (cherniavskii) [reply lib/src/utils/MuiPickersUtilsProvider.jsx]: Personally, I don't like passing moment instance to Utils.
I'd rather go for option №2, proposed by @alitaheri 

That being said, releasing it "as is" sounds reasonable for me too.
It has a drawback, since changing this may be a breaking change, but it's okay at least until mui is in beta.
