### PR TITLE
[529] Change moment locale example

### LINKED ISSUE #529: DatePicker Calendar is not changed by locale
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.11     |
| material-ui         |   1.4    |
| React               |     16.3.2    |
| Browser             |     Chrome    |
| Platform            |     Windows 10    |

## Steps to reproduce
1. Add MuiPickersUtilsProvider, MomentUtils, 
2. Add Button to toggle locale
3. CalenderHeaderText does not change.....?

## Expected behavior
All calendar should be changed by locale

## Actual behavior
Only day of week changed
screen

## Live example
https://codesandbox.io/s/p39xvj76jx

## Reference
https://github.com/dmtrKovalenko/material-ui-pickers/issues/383

### PR DESCRIPTION
**Pull request by josephMG**
- [x] I have changed my target branch to **develop** :facepunch: 

## Description
1. Modify BasePicker componentDidUpdate function;
2. Add example to change locale when using moment (like date-fns-localization)

### CODE REVIEW

File: docs/src/Examples/Localization/MomentLocalizationExample.jsx [hunk 1]
```diff
@@ -1,19 +1,91 @@
...
+    this.setState({
+      currentLocale: selectedLocale,
+      anchorEl: null,
+    });
+  }
+
+  render() {
+    const { selectedDate } = this.state;
+    const locale = localeMap[this.state.currentLocale];
+    moment.locale(locale);
```
Comment (dmtrKovalenko) [inline docs/src/Examples/Localization/MomentLocalizationExample.jsx]: Would be better to move this out to selectLocale function. This would be more obvious
