### PR TITLE
[#383] Migrate to React v16.3.0 context api

### LINKED ISSUE #383: Provided utils and locale changes are not received in pickers inside components using shouldComponentUpdate
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |rc7|

## Steps to reproduce
Set up like in docs and change locale prop

## Expected behavior
date-picker should re-render with new locale settings

## Actual behavior
date-picker won't recognize locale changes, MuiPickersUtilsProvider doesn't create a new Utils instance. I also found out, that MuiPickersUtilsProvider uses the legacy Provider API and it seems it doesn't pass down locale changes at all.

### PR DESCRIPTION
**Pull request by dmtrKovalenko**
- [x] I have changed my target branch to **develop** :facepunch: 

## Description
Migrate to the new official context api. @alitaheri would it break jalali utils?

### CODE REVIEW

**Comment by alitaheri** [comment]
Don't merge this before material-ui migrates too. We don't want to force React > 16.3 while material-ui supports React > 16.0.

Doing so, forces every one to migrate their react. Not that it's a bad thing, but I'm afraid it's simply soon for the community.

**Comment by dmtrKovalenko** [comment]
https://github.com/mui-org/material-ui/issues/10868

**Comment by Cretezy** [comment]
With `@material-ui/core` at `1.0.0-rc.0` now forcing React 16.3+, I think now is the time to merge this.

**Comment by alitaheri** [comment]
Yup, agreed 🎉 🎉 🎉

File: lib/src/_shared/WithUtils.jsx [hunk 1]
```diff
@@ -1,22 +1,16 @@
...
 const withUtils = () => (Component) => {
-  const WithUtils = ({ pickerRef, ...other }, context) => {
-    if (!context.muiPickersDateUtils) {
-      // eslint-disable-next-line no-console
-      console.error('Utils should be provided');
-    }
-
-    return <Component ref={pickerRef} utils={context.muiPickersDateUtils} {...other} />;
-  };
+  const WithUtils = ({ pickerRef, ...other }) => (
```
Comment (alitaheri) [inline lib/src/_shared/WithUtils.jsx]: You can [forward ref here](https://reactjs.org/docs/context.html#forwarding-refs-to-context-consumers) better do it now  that we are still in RC.

File: lib/src/utils/MuiPickersUtilsProvider.jsx [hunk 2]
```diff
@@ -14,18 +17,10 @@ export default class MuiPickersUtilsProvider extends Component {
...
-  }
-
-  getChildContext() {
+  render() {
     const { utils: Utils, locale, moment } = this.props;
-    return {
-      muiPickersDateUtils: new Utils({ locale, moment }),
-    };
-  }
+    const utils = new Utils({ locale, moment });
```
Comment (alitaheri) [inline lib/src/utils/MuiPickersUtilsProvider.jsx]: This can be put inside state and updated with `static getDerivedStateFromProps(nextProps, prevState)`. Having this inside render will cause cause all datepicker components to update. Because every time, utils will be a new instance and will force all consumers to update

Comment (dmtrKovalenko) [reply lib/src/utils/MuiPickersUtilsProvider.jsx]: Actually this do the trick. Because of provider will be rerendered when locale has been changed - every consumer will rerender and displayed up-to-date localized text.

**Comment by dmtrKovalenko** [comment]
@alitaheri Can you take a look of that?

File: docs/src/Examples/Guides/ControllingProgrammatically.jsx [hunk 3]
```diff
@@ -31,7 +31,7 @@ class ControllingProgrammaticallyExample extends PureComponent {
         <div className="picker">
           <DatePicker
             clearable
-            pickerRef={(node) => { this.picker = node; }}
+            ref={(node) => { this.picker = node; }}
```
Comment (cherniavskii) [inline docs/src/Examples/Guides/ControllingProgrammatically.jsx]: Is that a breaking change? If so, we should mention that in release notes

Comment (dmtrKovalenko) [reply docs/src/Examples/Guides/ControllingProgrammatically.jsx]: @cherniavskii thanks for good point. Surely will mention
